{{/*
Return the proper image name
Helper copied from bitnami/common: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_images.tpl
and modified to support global imageTag
{{ include "common.images.image" ( dict "imageRoot" .Values.path.to.the.image "global" .Values.global "image" .Values.image ) }}
*/}}
{{- define "nxCloud.images.common" }}
{{- $registryName := .imageRoot.registry }}
{{- $repositoryName := default .imageRoot.repository .global.imageRepository }}
{{- $imageName := .imageRoot.imageName }}
{{- $separator := ":" }}
{{- $termination := default .global.imageTag .imageRoot.tag | toString }}
{{- if .global }}
    {{- if .global.imageRegistry }}
     {{- $registryName = .global.imageRegistry }}
    {{- end }}
{{- end }}
{{- if .imageRoot.digest }}
    {{- $separator = "@" }}
    {{- $termination = .imageRoot.digest | toString }}
{{- end }}
{{- if $registryName }}
    {{- printf "%s/%s/%s%s%s" $registryName $repositoryName $imageName $separator $termination }}
{{- else }}
    {{- printf "%s/%s%s%s"  $repositoryName $imageName $separator $termination }}
{{- end }}
{{- end }}


{{/*
Return proper nx-cloud-workflow-controller image name
*/}}
{{- define "nxCloud.images.workflowController.image" }}
{{- include "nxCloud.images.common" (dict "imageRoot" .Values.controller.image "global" .Values.global) }}
{{- end }}