---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "nxCloud.app.labels" . | indent 4 }}
  name: nx-cloud-workflow-controller-rolebinding
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nx-cloud-workflow-controller-role
subjects:
  - kind: ServiceAccount
    name: nx-cloud-workflow-controller
    namespace: {{ .Values.global.namespace }}