---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nx-cloud-workflow-runner
  namespace: {{ .Values.global.namespace }}
  {{- if .Values.serviceAccounts.runner.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccounts.runner.annotations | nindent 4 }}
  {{- end }}
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "nxCloud.app.labels" . | indent 4 }}
  name: nx-cloud-workflow-controller
  namespace: {{ .Values.global.namespace }}
  {{- if .Values.serviceAccounts.controller.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccounts.controller.annotations | nindent 4 }}
  {{- end }}
  

