---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nx-cloud-workflow-runner
  namespace: {{ .Values.global.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "nxCloud.app.labels" . | indent 4 }}
  name: nx-cloud-workflow-controller
  namespace: {{ .Values.global.namespace }}

