{{- if and .Values.nxCloudWorkflows.enabled .Values.nxCloudWorkflows.externalName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nxCloudWorkflows.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nx-cloud-workflow-controller
    {{- include "nxCloud.app.labels" . | indent 4 }}
spec:
  {{- if .Values.nxCloudWorkflows.externalName }}
  type: ExternalName
  externalName: {{ .Values.nxCloudWorkflows.externalName }}
  {{- end }}
{{- end }}
